import { useMemo, useState } from "react";
import { useUser } from "@clerk/react";
import { BookOpen, CheckCircle2, ClipboardPenLine, GraduationCap, LineChart, Save, ShieldAlert, Users } from "lucide-react";
import { toast } from "sonner";
import { LearningShell } from "@/components/LearningShell";
import { MathFormula } from "@/components/MathFormula";
import { useAuth } from "@/_core/hooks/useAuth";
import { learningUnits } from "@shared/learningContent";
import { trpc } from "@/lib/trpc";

const initialQuestion = { unitId: "unit-errors", lessonId: "rounding-rules", questionType: "numeric" as const, title: "", prompt: "", answerSchemaJson: '{\n  "expectedValue": 0,\n  "tolerance": 0.001\n}', tolerance: "0.001", explanation: "", correctStep: "", isPublished: true, sortOrder: 1 };
const initialLesson = { unitId: "unit-errors", title: "", summary: "", contentJson: '{\n  "formulas": [],\n  "examples": []\n}', visualizationType: "" as "" | "interpolation" | "integration" | "newton" | "euler", visualizationConfigJson: "{}", isPublished: true, sortOrder: 1 };

export default function TeacherPage() {
  const { user, isAuthenticated, startSignIn } = useAuth();
  const { user: clerkUser } = useUser();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const dashboard = trpc.teacher.dashboard.useQuery(undefined, { enabled: isAdmin });
  const saveQuestion = trpc.teacher.saveQuestion.useMutation({ onSuccess: () => { toast.success("تم حفظ السؤال"); utils.teacher.dashboard.invalidate(); } });
  const saveLesson = trpc.teacher.saveLesson.useMutation({ onSuccess: () => { toast.success("تم حفظ الدرس"); utils.teacher.dashboard.invalidate(); } });
  const [question, setQuestion] = useState(initialQuestion);
  const [lesson, setLesson] = useState(initialLesson);
  const selectedUnit = useMemo(() => learningUnits.find(unit => unit.id === question.unitId), [question.unitId]);

  const submitQuestion = (event: React.FormEvent) => {
    event.preventDefault();
    try { JSON.parse(question.answerSchemaJson); } catch { toast.error("تحقق من صحة JSON الخاص بالإجابة."); return; }
    saveQuestion.mutate(question);
  };
  const submitLesson = (event: React.FormEvent) => {
    event.preventDefault();
    try { JSON.parse(lesson.contentJson); JSON.parse(lesson.visualizationConfigJson); } catch { toast.error("تحقق من صحة JSON الخاص بمحتوى الدرس أو الرسم."); return; }
    saveLesson.mutate(lesson);
  };

  if (!isAuthenticated) return <LearningShell><section className="teacher-gate page-width"><ShieldAlert size={28} /><h1>تسجيل الدخول مطلوب</h1><p>سجّل الدخول بحساب المدرس للوصول إلى المحتوى، إعدادات التصحيح، ونتائج الطلاب.</p><button type="button" className="primary-button" onClick={startSignIn}>تسجيل الدخول</button></section></LearningShell>;
  if (!isAdmin) return <LearningShell><section className="teacher-gate page-width"><ShieldAlert size={28} /><h1>هذه المساحة للمدرس فقط</h1><p>تم تسجيل دخولك بنجاح، لكن حسابك لا يحمل دور المدرس بعد. أضف معرّف Clerk التالي إلى المتغير الآمن <code>CLERK_ADMIN_USER_ID</code> ثم أعد تشغيل الخادم.</p><code className="clerk-id">{clerkUser?.id ?? "جارٍ قراءة المعرّف…"}</code></section></LearningShell>;

  const publishedQuestions = dashboard.data?.questions.filter(item => item.isPublished === 1).length ?? 0;
  return <LearningShell><section className="teacher-hero page-width"><div><span className="eyebrow">لوحة المدرس</span><h1>محتوى مضبوط،<br />وتغذية راجعة أدق.</h1><p>أنشئ درسًا أو سؤالًا، واضبط صيغة الإجابة وهامش التفاوت، ثم راقب نشاط الطلاب من مكان واحد.</p></div><div className="teacher-stats"><article><Users size={19} /><strong>{dashboard.data?.students.length ?? 0}</strong><span>طالب مسجل</span></article><article><ClipboardPenLine size={19} /><strong>{dashboard.data?.questions.length ?? 0}</strong><span>سؤال مؤلف</span></article><article><CheckCircle2 size={19} /><strong>{publishedQuestions}</strong><span>سؤال منشور</span></article></div></section>
    <section className="teacher-layout page-width"><div className="teacher-workspace"><form className="author-card" onSubmit={submitQuestion}><div className="author-card__head"><ClipboardPenLine size={20} /><div><span>محرر المسائل</span><h2>أنشئ سؤالًا قابلًا للتصحيح</h2></div></div><div className="form-grid"><label>الوحدة<select value={question.unitId} onChange={event => { const unitId = event.target.value; setQuestion(current => ({ ...current, unitId, lessonId: learningUnits.find(unit => unit.id === unitId)?.lessons[0]?.id ?? "" })); }}>{learningUnits.map(unit => <option key={unit.id} value={unit.id}>{unit.title}</option>)}</select></label><label>الدرس<select value={question.lessonId} onChange={event => setQuestion(current => ({ ...current, lessonId: event.target.value }))}>{selectedUnit?.lessons.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>نوع السؤال<select value={question.questionType} onChange={event => setQuestion(current => ({ ...current, questionType: event.target.value as typeof current.questionType }))}><option value="numeric">إجابة عددية</option><option value="choice">اختيار من متعدد</option><option value="table">إكمال جدول</option><option value="multiStep">متعدد الخطوات</option></select></label><label>ترتيب العرض<input type="number" min="1" value={question.sortOrder} onChange={event => setQuestion(current => ({ ...current, sortOrder: Number(event.target.value) }))} /></label></div><label>عنوان السؤال<input value={question.title} onChange={event => setQuestion(current => ({ ...current, title: event.target.value }))} placeholder="مثال: تقدير خطأ التقريب" required /></label><label>نص المسألة<textarea value={question.prompt} onChange={event => setQuestion(current => ({ ...current, prompt: event.target.value }))} placeholder="اكتب نص المسألة بالعربية، ويمكنك تضمين LaTeX مثل \frac{h}{2}" required /></label><div className="form-grid"><label>هامش التفاوت<input value={question.tolerance} onChange={event => setQuestion(current => ({ ...current, tolerance: event.target.value }))} placeholder="0.001" /></label><label className="switch-label"><input type="checkbox" checked={question.isPublished} onChange={event => setQuestion(current => ({ ...current, isPublished: event.target.checked }))} /> منشور للطلاب</label></div><label>مخطط الإجابة (JSON)<textarea className="code-input" value={question.answerSchemaJson} onChange={event => setQuestion(current => ({ ...current, answerSchemaJson: event.target.value }))} required /></label><label>الشرح بعد المحاولة<textarea value={question.explanation} onChange={event => setQuestion(current => ({ ...current, explanation: event.target.value }))} /></label><label>الخطوة الصحيحة<textarea value={question.correctStep} onChange={event => setQuestion(current => ({ ...current, correctStep: event.target.value }))} /></label><button className="primary-button" disabled={saveQuestion.isPending}><Save size={16} /> حفظ السؤال</button></form>
      <form className="author-card" onSubmit={submitLesson}><div className="author-card__head"><BookOpen size={20} /><div><span>محرر الدروس</span><h2>أضف محتوى ورسمًا مرفقًا</h2></div></div><div className="form-grid"><label>الوحدة<select value={lesson.unitId} onChange={event => setLesson(current => ({ ...current, unitId: event.target.value }))}>{learningUnits.map(unit => <option key={unit.id} value={unit.id}>{unit.title}</option>)}</select></label><label>ترتيب العرض<input type="number" min="1" value={lesson.sortOrder} onChange={event => setLesson(current => ({ ...current, sortOrder: Number(event.target.value) }))} /></label></div><label>عنوان الدرس<input value={lesson.title} onChange={event => setLesson(current => ({ ...current, title: event.target.value }))} required /></label><label>ملخص الدرس<textarea value={lesson.summary} onChange={event => setLesson(current => ({ ...current, summary: event.target.value }))} /></label><label>محتوى منظم (JSON)<textarea className="code-input" value={lesson.contentJson} onChange={event => setLesson(current => ({ ...current, contentJson: event.target.value }))} /></label><div className="form-grid"><label>الرسم التفاعلي<select value={lesson.visualizationType} onChange={event => setLesson(current => ({ ...current, visualizationType: event.target.value as typeof current.visualizationType }))}><option value="">بدون رسم</option><option value="interpolation">الاستيفاء</option><option value="integration">التكامل العددي</option><option value="newton">نيوتن</option><option value="euler">أويلر</option></select></label><label className="switch-label"><input type="checkbox" checked={lesson.isPublished} onChange={event => setLesson(current => ({ ...current, isPublished: event.target.checked }))} /> منشور للطلاب</label></div><label>إعدادات الرسم (JSON)<textarea className="code-input" value={lesson.visualizationConfigJson} onChange={event => setLesson(current => ({ ...current, visualizationConfigJson: event.target.value }))} /></label><button className="primary-button" disabled={saveLesson.isPending}><Save size={16} /> حفظ الدرس</button></form></div>
      <aside className="teacher-sidebar"><article><GraduationCap size={20} /><strong>قواعد التصحيح</strong><p>اكتب القيمة المتوقعة وهامش التفاوت في JSON، ليبقى التصحيح العددي متسامحًا مع التقريب.</p><MathFormula latex="|x-x_0|\\leq\\varepsilon" display={false} /></article><article><LineChart size={20} /><strong>ملخص النشاط</strong><p>{dashboard.data?.recentAttempts.length ?? 0} محاولة حديثة محفوظة في قاعدة البيانات.</p></article><article><strong>الأسئلة الأخيرة</strong><div className="teacher-mini-list">{dashboard.data?.questions.slice(0, 6).map(item => <span key={item.id}>{item.title ?? item.id}</span>) ?? <span>جارٍ تحميل الأسئلة…</span>}</div></article></aside></section></LearningShell>;
}
